/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rosshamish_DataSorterBackup */

#ifndef _Included_rosshamish_DataSorterBackup
#define _Included_rosshamish_DataSorterBackup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rosshamish_DataSorterBackup
 * Method:    sortData_C
 * Signature: (Ljava/lang/String;Ljava/lang/String;DI)V
 */
JNIEXPORT void JNICALL Java_rosshamish_DataSorterBackup_sortData_1C
  (JNIEnv *, jobject, jstring, jstring, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
